workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd flutter
          flutter pub get
          flutter build ios-framework
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          cd flutter
          flutter build ios --release --no-codesign
    artifacts:
      - flutter/build/ios/iphoneos/*.app
     
